blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/watchapi/watchapi-client-support/discussions
    about: Ask questions or discuss ideas with the community
  - name: Documentation
    url: https://watchapi.dev/docs
    about: Check the documentation for guides and API reference
