blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://discord.gg/5bANxHbfNx
    about: Ask questions or discuss ideas with the community
  - name: Documentation
    url: https://docs.watchapi.dev
    about: Check the documentation for guides and API reference
